# Generated by Django 4.2 on 2024-11-05 22:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("address", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "user_base",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "userbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="users.userbase",
                    ),
                ),
            ],
            options={
                "db_table": "user",
            },
            bases=("users.userbase",),
        ),
    ]
