# Generated by Django 4.2 on 2025-01-17 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountBase",
            fields=[
                (
                    "account_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("checking", "Checking"),
                            ("savings", "Savings"),
                            ("custody", "Custody"),
                        ],
                        default="checking",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "account_base",
                "swappable": "ACCOUNT_MODEL",
            },
        ),
        migrations.CreateModel(
            name="CheckingAccount",
            fields=[
                (
                    "accountbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.ACCOUNT_MODEL,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("PIN", models.CharField(max_length=4)),
            ],
            options={
                "db_table": "account_checking",
            },
            bases=("accounts.accountbase",),
        ),
        migrations.CreateModel(
            name="CustodyAccount",
            fields=[
                (
                    "accountbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.ACCOUNT_MODEL,
                    ),
                ),
                (
                    "unique_identifier",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the bank's custody account ('bank_custody_account').",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "db_table": "account_custody",
            },
            bases=("accounts.accountbase",),
        ),
        migrations.CreateModel(
            name="SavingsAccount",
            fields=[
                (
                    "accountbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to=settings.ACCOUNT_MODEL,
                    ),
                ),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
            options={
                "db_table": "account_savings",
            },
            bases=("accounts.accountbase",),
        ),
    ]
