# Generated by Django 4.2 on 2025-01-17 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.CUSTOMER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountbase",
            name="customer_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to=settings.CUSTOMER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="savingsaccount",
            name="reference_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.checkingaccount",
            ),
        ),
        migrations.AddField(
            model_name="custodyaccount",
            name="reference_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.checkingaccount",
            ),
        ),
    ]
