# Generated by Django 4.2 on 2025-01-17 14:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "date",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
                (
                    "sending_account_id",
                    models.UUIDField(
                        blank=True, help_text="UUID of the sending account", null=True
                    ),
                ),
                (
                    "receiving_account_id",
                    models.UUIDField(
                        blank=True, help_text="UUID of the receiving account", null=True
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
            },
        ),
        migrations.CreateModel(
            name="ATMTransaction",
            fields=[
                (
                    "transaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transactions.transaction",
                    ),
                ),
                (
                    "atmId",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
            options={
                "db_table": "transaction_atm",
            },
            bases=("transactions.transaction",),
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "transaction_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="transactions.transaction",
                    ),
                ),
                (
                    "stockId",
                    models.UUIDField(blank=True, help_text="Stock Id", null=True),
                ),
                ("quantity", models.IntegerField()),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell")], max_length=4
                    ),
                ),
            ],
            options={
                "db_table": "transaction_stock",
            },
            bases=("transactions.transaction",),
        ),
    ]
